"""Add date column to sales_returns

Revision ID: 3de504618434
Revises: 689517ec5db6
Create Date: 2025-01-23 17:22:33.039546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3de504618434'
down_revision = '689517ec5db6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_returns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_returns', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###
