"""Fix shop_id duplication in Income model

Revision ID: 81aad297734a
Revises: 8a2f6009bb44
Create Date: 2025-01-22 23:44:19.530573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81aad297734a'
down_revision = '8a2f6009bb44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.drop_constraint('income_shop_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'shop', ['shop_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('income_shop_id_fkey', 'shop', ['shop_id'], ['id'])

    # ### end Alembic commands ###
