"""Add Expense table

Revision ID: 8a2f6009bb44
Revises: 86e122fcdbee
Create Date: 2025-01-22 22:06:23.479466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a2f6009bb44'
down_revision = '86e122fcdbee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.drop_column('notes')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
