"""Add shop_expenses table

Revision ID: 8f75c1bd35d5
Revises: 3de504618434
Create Date: 2025-01-23 17:29:52.660685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f75c1bd35d5'
down_revision = '3de504618434'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('purchase', sa.Float(), nullable=True),
    sa.Column('store_needs', sa.Float(), nullable=True),
    sa.Column('salary', sa.Float(), nullable=True),
    sa.Column('rent', sa.Float(), nullable=True),
    sa.Column('repair', sa.Float(), nullable=True),
    sa.Column('marketing', sa.Float(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shop_expenses')
    # ### end Alembic commands ###
