"""Добавлены поля hours_worked и motivation в Employee

Revision ID: d7f52aecb9a9
Revises: c70d343418f2
Create Date: 2025-01-22 00:40:20.086147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7f52aecb9a9'
down_revision = 'c70d343418f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hours_worked', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('motivation', sa.Float(), nullable=True))
        batch_op.drop_column('position')
        batch_op.drop_column('work_days')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('work_days', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('position', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_column('motivation')
        batch_op.drop_column('hours_worked')

    # ### end Alembic commands ###
