"""Add description columns to shop_expenses

Revision ID: e07c780d1183
Revises: 8f75c1bd35d5
Create Date: 2025-01-23 17:37:40.947523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e07c780d1183'
down_revision = '8f75c1bd35d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shop_expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchase_desc', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('store_needs_desc', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('salary_desc', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('rent_desc', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('repair_desc', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('marketing_desc', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shop_expenses', schema=None) as batch_op:
        batch_op.drop_column('marketing_desc')
        batch_op.drop_column('repair_desc')
        batch_op.drop_column('rent_desc')
        batch_op.drop_column('salary_desc')
        batch_op.drop_column('store_needs_desc')
        batch_op.drop_column('purchase_desc')

    # ### end Alembic commands ###
