"""Начальная миграция

Revision ID: e2b14ee12296
Revises: 
Create Date: 2025-01-22 13:56:15.018961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2b14ee12296'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('month', sa.String(length=7), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_column('month')

    # ### end Alembic commands ###
